name: firetell_flutter_sdk_example
description: Example app demonstrating Firetell Flutter SDK usage.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firetell_flutter_sdk:
    path: ../
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_callkit_incoming: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
