name: firetell_flutter_sdk
description: >
  Firetell WebRTC VoIP SDK for Flutter — audio and video calls and VoIP push notifications (FCM & APNs) with native WebSocket event-based signaling.
version: 1.1.1
homepage: https://firetell.com
repository: https://github.com/firetellcom/firetell-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.6.2
  web_socket_channel: ^3.0.3
  http: ^1.6.0
  uuid: ^4.6.0
  shared_preferences: ^2.5.5
  flutter_callkit_incoming: ^3.1.5
  device_info_plus: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
